import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage();
await page.goto('http://localhost:8080/login', { waitUntil: 'networkidle' });
await page.fill('input[type="email"]', 'quanly@hcare.com');
await page.fill('input[type="password"]', 'hcare123');
await page.click('button[type="submit"]');
await page.waitForTimeout(2000);
await page.goto('http://localhost:8080/apartments', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
await page.click('a:has-text("B-34.09")');
await page.waitForTimeout(2000);
const owner = await page.inputValue('input[name="ownerName"]');
const rent = await page.inputValue('input[name="ownerRent"]');
const tenant = await page.inputValue('input[name="tenantName"]');
console.log('ownerName:', owner);
console.log('ownerRent:', rent);
console.log('tenantName:', tenant);
await browser.close();
