import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true });
const page = await ctx.newPage();
page.on('dialog', async (d) => {
  if (d.type() === 'prompt') await d.accept('E2E-TEST-99');
  else await d.accept();
});
await page.goto('http://localhost:8080/login');
await page.fill('input[type="email"]', 'quanly@hcare.com');
await page.fill('input[type="password"]', 'hcare123');
await page.click('button[type="submit"]');
await page.waitForURL('**/', { timeout: 15000 });
await page.goto('http://localhost:8080/apartments');
await page.waitForSelector('button:has-text("Thêm Căn")', { timeout: 10000 });
console.log('Nút Thêm Căn: OK');
await page.click('button:has-text("Thêm Căn")');
await page.waitForURL('**/apartments/**', { timeout: 10000 });
await page.waitForTimeout(1500);
console.log('Tạo căn + vào trang chi tiết:', page.url().includes('/apartments/') ? 'OK' : 'FAIL');
const nameInput = await page.locator('input[name="name"]').inputValue();
console.log('Ô Mã Căn hiện:', nameInput === 'E2E-TEST-99' ? 'OK' : 'FAIL (' + nameInput + ')');
const delBtn = await page.locator('button:has-text("Xóa căn hộ này")').count();
console.log('Nút xóa hiện:', delBtn > 0 ? 'OK' : 'FAIL');
await page.screenshot({ path: '/tmp/apt_new.png' });
await page.click('button:has-text("Xóa căn hộ này")');
await page.waitForURL('**/apartments', { timeout: 10000 });
console.log('Xóa căn → quay về danh sách: OK');
await browser.close();
