import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true });
const page = await ctx.newPage();
await page.goto('http://localhost:8080/portal/login');
await page.fill('input[type="text"]', 'test-tenant@example.com');
await page.fill('input[type="password"]', 'test123');
await page.click('button[type="submit"]');
await page.waitForURL('**/portal', { timeout: 10000 });
await page.waitForTimeout(1500);
console.log('Dự án hiện:', await page.locator('text=Masteri An Phú').count() > 0 ? 'OK' : 'FAIL');
console.log('Địa chỉ hiện:', await page.locator('text=Thảo Điền').count() > 0 ? 'OK' : 'FAIL');
console.log('Giá 18tr hiện:', await page.locator('text=18,000,000').count() > 0 ? 'OK' : 'FAIL');
console.log('Nút Photos:', await page.locator('a:has-text("Photos")').count());
console.log('Nút Map:', await page.locator('a:has-text("Map")').count());
console.log('Badge Available:', await page.locator('text=Available now').count());
const el = await page.locator('text=Other Apartments');
await el.scrollIntoViewIfNeeded();
await page.screenshot({ path: '/tmp/v_cards.png', fullPage: true });
await browser.close();
